bessel_regression:
  epochs: 20000
  method: grid
  parameters:
    N_max:
      values: [64, 128, 256, 512, 1024]
    n_samples:
      values: [1000, 10000, 100000]
    learning_rate:
      values: [1e-4, 3e-4, 1e-3]

spiral_classification:
  epochs: 20000
  method: grid
  parameters:
    n_classes:
      values: [3, 5, 7, 9]
    N_max:
      values: [64, 128, 256, 512, 1024]
    learning_rate:
      values: [1e-4, 3e-4, 1e-3]