bessel_regression:
  epochs: 5000
  num_runs: 10
  base_seed: 0
  method: grid
  parameters:
    N_max:
      values: [2, 4, 6, 8, 11, 16, 23, 32, 45, 64, 91, 128, 181, 256, 363, 512, 724, 1024]
    n_samples:
      values: [32768]
    learning_rate:
      values: [1e-4, 3e-4, 5e-4, 6e-4, 1e-3, 0.01, 0.1]

bessel_regression_baseline:
  epochs: 5000
  num_runs: 10
  base_seed: 0
  method: grid
  parameters:
    N_max:
      values: [2, 4, 6, 8, 11, 16, 23, 32, 45, 64, 91, 128, 181, 256, 363, 512, 724, 1024]
    n_samples:
      values: [32768]
    learning_rate:
      values: [1e-4, 3e-4, 5e-4, 6e-4, 1e-3, 0.01, 0.1]

gaussian_regression:
  epochs: 100_000
  num_runs: 10
  base_seed: 0
  method: grid
  parameters:
    N_max:
      values: [2, 4, 6, 8, 11, 16, 23, 32, 45, 64, 91, 128, 181, 256, 363, 512, 724, 1024]
    n_samples:
      values: [32768]
    noise_level:
      values: [0.01]
    learning_rate:
      values: [1e-4, 3e-4, 5e-4, 6e-4, 1e-3, 0.01, 0.1]

gaussian_regression_baseline:
  epochs: 100_000
  num_runs: 10
  base_seed: 0
  method: grid
  parameters:
    N_max:
      values: [2, 4, 6, 8, 11, 16, 23, 32, 45, 64, 91, 128, 181, 256, 363, 512, 724, 1024]
    n_samples:
      values: [32768]
    noise_level:
      values: [0.01]
    learning_rate:
      values: [1e-4, 3e-4, 5e-4, 6e-4, 1e-3, 0.01, 0.1]

spiral_classification:
  epochs: 5000
  num_runs: 10
  base_seed: 0
  method: grid
  parameters:
    n_classes:
      values: [3, 5, 7, 9]
    N_max:
      values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
    learning_rate:
      values: [1e-4, 3e-4, 1e-3]

spiral_classification_baseline:
  epochs: 5000
  num_runs: 10
  base_seed: 0
  method: grid
  parameters:
    n_classes:
      values: [3, 5, 7, 9]
    N_max:
      values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
    learning_rate:
      values: [1e-4, 3e-4, 1e-3]